package model

const (
	DEFINE_TYPE_ENUM   = "enum"
	DEFINE_TYPE_STRUCT = "struct"
	DEFINE_TYPE_CONST  = "const"

	DEFINE_COLUMN_COUNT = 6

	DEFINE_CATEGORY_NAME_INDEX  = 0
	DEFINE_COLUMN_NAME_INDEX    = 1
	DEFINE_COLUMN_FIELD_INDEX   = 2
	DEFINE_COLUMN_TYPE_INDEX    = 3
	DEFINE_COLUMN_VALUE_INDEX   = 4
	DEFINE_COLUMN_COMMENT_INDEX = 5
)

var (
	DATA_ROW_DESC_INDEX  = 0
	DATA_ROW_TYPE_INDEX  = 1
	DATA_ROW_CS_INDEX    = 2
	DATA_ROW_FIELD_INDEX = 3

	FixedRowCount = 4
)
